index:
  success: List of all the birds.
create:
  success: Bird record has successfully created.
show:
  success: Details of a single bird.
  failure: Record not found.
destroy:
  success: Bird record has successfully deleted.
  failure: Record not found.
